### PR TITLE
Get ACA model from chandra_models repo via xija code

### PR DESCRIPTION
**Pull request by jeanconn**
Get ACA model from chandra_models repo via xija code

No unit tests.

For functional tests I ran the code to a temporary web directory and it ran fine and grabbed the right version of the model (I stuck in the chandra_models version over on the Y axis label).

### CODE REVIEW

**Comment by jeanconn** [comment]
ccd_temp_all

**Review by taldcroft — COMMENTED** [review]
Looks good, but why not put the model version in the title instead of y-axis? Maybe `f'ACA model {model_version} vs. telemetry'`.

**Comment by jeanconn** [comment]
Sure.  Mostly I was just thinking that I wanted a low-impact change and this was closest to a watermark if I stuck it over on the left.  And it isn't really a versus plot but sure.

**Comment by jeanconn** [comment]
ccd_temp_all

**Comment by taldcroft** [comment]
I went back and forth several times on "model and telemetry" or "model vs. telemetry". I know the latter is not technically correct, but the intent of the plot is to compare model to telemetry. Anyway... :smile:

I don't know what being close to a watermark means.

**Comment by taldcroft** [comment]
If you prefer "and" then go for it.

**Comment by jeanconn** [comment]
By "close to a watermark" I just meant "some extra information that somebody could find if they went looking for it".  And I'm fine with just blaming you if anybody in SSAWG gives me a hard time on vs :smile:

**Pull request merged**
