### PR TITLE
Py3, flake8, make a package, and remove characteristics

### PR DESCRIPTION
**Pull request by jeanconn**
Py3, flake8, make a package, and remove characteristics

Right now this is reading the aca model spec from the starcheck package installed in SKA but the plan would be to set it to use the new xija code (previously it was using chandra_models directly, but I'm getting the impression we don't want to install that as a package).

Like the Ska.report_ranges update (that was prompted by this), this doesn't clean up the old cruft (or bad logic or old formatted strings), but does make the code use the right modules (for example, kadi commanded states and no sybase).

### CODE REVIEW

**Comment by taldcroft** [comment]
This looks reasonable from a 2-minute glance.  What about testing (install and functionality thereafter)?

**Comment by jeanconn** [comment]
That's somewhat a question of "what do we want?".  I ran it on the side from the beginning of the year with a local rename of the task from "perigee_health_plots" to "perigee_health_plots_py3" to make

https://cxc.cfa.harvard.edu/mta/ASPECT/perigee_health_plots_py3/

But if figured in the end we'd probably want this new code to just write into the old area but not overwrite the old months.
And then I don't know what our plan is for ska3 or shiny crontasks stuff just now.  This could run out of ska3 if we make a package for Ska.report_ranges, make this a conda package too, and install in ska3-flight.  Otherwise, similar process for shiny.  The ska2 perigee_health_plots job is disabled by heart attack now I think.

**Review by javierggt — COMMENTED** [review]
Same here: I think we would need .git_archival.txt and .gitattributes files

**Comment by jeanconn** [comment]
Sure.  Files added (though we probably need a good demo package so I will stop forgetting.  I suppose I could have pushed those directly to master too as they aren't controversial or really tied to the PR).

**Review by taldcroft — APPROVED** [review]
Looks fine to me. For something like this the proof is in the pudding, to see if all the downstream machinery works on this to get a functioning installed package in shiny. Since there is no real consequence if it fails I would say to just merge this now.

**Comment by jeanconn** [comment]
The proof is always in the eating.

Anyway, I don't actually know what is running for shiny build for downstream machinery.  I was tossing stuff into the build list because I saw that in the old build :

https://github.com/sot/skare3_tools/blob/master/docker/centos5-builder/files/build.sh

but I don't know how to test-sort-of-alike at this point for shiny.

**Comment by jeanconn** [comment]
And yeah, this all still looks broken: I'm having trouble with SCM finding a version on the conda-built package.  I thought perhaps I needed to make a release (and might as well merge and do it from master) so I did that, but will need more changes for it to work.

**Pull request merged**
