### PR TITLE
Include all hdr3 8x8 data in plots

### PR DESCRIPTION
**Pull request by jeanconn**
## Description
Include all hdr3/8x8 data in plots

## Interface impacts

This PR breaks the data into orbits instead of by contiguous ERs (perigee passes).
The project itself might need more renaming and reoganizing.

### Unit tests

- [x] No unit tests

### Functional tests

```
python -m perigee_health_plots.pass_plots --start_time 2023:250 --web_dir web --data_dir data --web_server https://icxc.cfa.harvard.edu/ --url_dir /aspect/test_review_outputs/perigee_health_plots-pr23/web/
```
https://icxc.cfa.harvard.edu/aspect/test_review_outputs/perigee_health_plots-pr23/web/

### CODE REVIEW

**Comment by taldcroft** [comment]
Is this ready for review?

**Comment by jeanconn** [comment]
Sure.  It works for what it does.  I was thinking with non-fsds that we might be able to do more incremental improvements.

**Review by taldcroft — COMMENTED** [review]
Looks good. The only thing to change is not exactly related, but the CCD temperature model and data plot should follow the standard color convention (model=red telemetry=blue) for thermal dashboard plots. As it is the blue/black scheme makes it pretty difficult to see the model.

**Comment by jeanconn** [comment]
I updated the colors and redid the functional output.  I left the telemetry as dots -- let me know if it is required they be non-dots.

**Review by taldcroft — APPROVED** [review]
Looks great!

**Pull request merged**
